name: paisa
description: Smart Investment Platform.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  #http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  smooth_page_indicator: ^1.1.0
  animate_do: any
  iconsax: ^0.0.8
  fl_chart: ^0.40.0 #remove this later
  syncfusion_flutter_charts: ^24.2.4+3
  cupertino_icons: ^1.0.2
  #flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.2
  pinput: ^3.0.1
  webview_flutter: ^3.0.4
  any_link_preview: ^3.0.1
  web_socket_channel: ^2.4.0
  #flutter_local_notifications: ^16.1.0
  awesome_notifications: ^0.8.2
  #awesome_notifications_core: ^0.9.0
  image_picker: ^1.0.4
  page_view_indicators: ^2.0.0 #for search dot
  flutter_spinkit: ^5.1.0 #for loading animation

  #salomon_bottom_bar: ^3.3.2 //looked ugly, switched to default bottom navigation
  crypto: ^3.0.1
  babstrap_settings_screen: ^0.1.6
  flutter_slidable: ^3.0.1
  #autocomplete_textfield: ^2.0.1
  #freezed: ^2.4.5
  json_annotation: ^4.8.1
  #freezed_annotation: ^2.4.1
  path_provider: ^2.1.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  dio: ^5.4.0
  uuid: ^4.2.2
  equatable: ^2.0.5
  #connectivity_plus: ^5.0.2
  internet_connection_checker_plus: ^2.2.0
  lottie: ^2.7.0
  pretty_dio_logger: ^1.3.1
  awesome_dio_interceptor: ^1.0.0
  #multi_select_flutter: ^4.1.3
  #collection: ^1.18.0
  jwt_decoder: ^2.0.1
  #dart_ping: ^9.0.1
  #internet_connection_checker: ^1.0.0+1
  social_login_buttons: ^1.0.7
  #google_sign_in: ^6.2.1
  permission_handler: ^11.2.0
  #sensors_plus: ^4.0.2
  local_auth: ^2.1.8
  all_sensors2: ^1.0.1
  animated_text_kit: ^4.2.2 #for animated text in on splash
  #shake: ^2.2.0 #dependency for shake detection //depends in sensors_plus
  #pulsator: ^1.0.0+2 # for pulsating icon in home
  flutter_typeahead: ^5.2.0 #for search bar, type and search functionality
  #shimmer: ^3.0.0
  animations: ^2.0.11 #for page transition animation
  mockito: ^5.4.4 # for testing
  skeletonizer: ^1.0.1 #for skeleton loading
  #awesome_flutter_extensions: ^1.2.0
  test_cov_console: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  snippet_coder_utils: ^1.0.14
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  hive_generator: ^2.0.1

#--------------- ./ PACKAGES END ------------------#

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/
    - assets/logos/logo.png
    - assets/images/worldwide.png
    - assets/images/no-internet.png
    - assets/animation/loading/loading1.json
    - assets/animation/others/others (4).json
    - assets/animation/others/others (2).json
    - assets/animation/others/others (3).json
    - assets/animation/notfound/404.json
    - assets/images/
    - assets/logos/
    - assets/images/content/
    - assets/images/on_boarding_images/
    - assets/images/paymentgateways/khalti.png
    - assets/images/paymentgateways/esewa.png
    - test_data/index_test.json
    - test_data/auth_test_data.json
    - test_data/watchlist_test_data.json
    - test_data/portfolio_test.json
    - test_data/portfolio_data_test.json
    - test_data/stock_test_data.json
    - test_data/commodity_test_data.json
    - test_data/news_test_data.json
